#!/usr/bin/env tsx
// ============================================================================
// ingest-settlements.ts
// Pulls SP-API V2 settlement reports into brain.settlements +
// brain.settlement_lines.
//
// What this is for: the authoritative record of cash landing in our bank
// account from Amazon. Powers analytics.cash_position_current (PR #84) and
// the /wbr cash section.
//
// Settlements are AUTO-GENERATED by Amazon (~one per 14-day cycle per
// marketplace), so this CLI does not call createReport. It discovers
// available reports via listReports and downloads each one not yet in
// raw.sp_api_report.
//
// Usage:
//   npm run ingest-settlements                                # last 180 days
//   npm run ingest-settlements -- --days 30                   # narrower window
//   npm run ingest-settlements -- --since 2026-01-01          # explicit date
//   npm run ingest-settlements -- --region na                 # NA region
//   npm run ingest-settlements -- --marketplace-id A1F83G8C2ARO7P
//   npm run ingest-settlements -- --dry-run                   # list, don't fetch
//
// Performance note: first run pulls ~180 days × N marketplaces of settlements,
// each containing thousands of transaction lines. Settlements themselves are
// few (~13 per marketplace per 180d), but lines can run to tens of thousands.
// Wall-clock dominated by document fetch + per-line INSERTs; expect 5-15 min
// on first run, <1 min on incremental runs.
// ============================================================================

import { parseArgs } from 'node:util';
import { loadEnvForAmazonShared, getSpApiRegionConfig, type SpApiRegion } from '../lib/env.js';
import { getPgClient } from '../lib/supabase.js';
import { SpApiClient } from '../lib/sp-api/client.js';
import { ingestSettlementsWindow } from '../lib/sp-api/settlements.js';

async function main(): Promise<void> {
  const { values } = parseArgs({
    options: {
      since:              { type: 'string' },
      days:               { type: 'string' },
      region:             { type: 'string' },
      'marketplace-id':   { type: 'string' },
      'dry-run':          { type: 'boolean', default: false },
    },
  });

  const sinceDate = values.since ? new Date(values.since + 'T00:00:00Z') : null;
  const days = values.days ? parseInt(values.days, 10) : null;
  if (sinceDate && days !== null) {
    throw new Error('Use either --since OR --days, not both.');
  }
  if (days !== null && (!Number.isFinite(days) || days < 1)) {
    throw new Error('--days must be a positive integer.');
  }

  const env = loadEnvForAmazonShared();
  let region: SpApiRegion = env.SP_API_REGION;
  if (values.region !== undefined) {
    if (values.region !== 'na' && values.region !== 'eu' && values.region !== 'fe') {
      throw new Error(`--region must be one of: na, eu, fe. Got "${values.region}".`);
    }
    region = values.region;
  }
  const regionConfig = getSpApiRegionConfig(region, env);

  // Default --since: 180 days back from "now".
  const effectiveSince = sinceDate
    ?? new Date(Date.now() - (days ?? 180) * 86_400_000);

  // Marketplace filter: if user provides --marketplace-id, use just that;
  // otherwise let the call return all marketplaces accessible to the LWA app
  // for this region. listReports's marketplaceIds is a server-side filter; if
  // we don't send it, Amazon returns all.
  const marketplaceIds = values['marketplace-id']
    ? [values['marketplace-id']]
    : regionConfig.marketplaceIds;

  console.log('operator-datacore — Amazon Settlements ingest');
  console.log('---------------------------------------------');
  console.log(`  Region:           ${regionConfig.region}`);
  console.log(`  Marketplace IDs:  ${marketplaceIds.join(', ')}`);
  console.log(`  Created since:    ${effectiveSince.toISOString()}`);
  console.log(`  Dry run:          ${values['dry-run']}`);
  console.log('');

  if (values['dry-run']) {
    console.log('--dry-run set — would call listReports + iterate; no document fetch, no DB writes.');
    return;
  }

  const spClient = new SpApiClient({
    region: regionConfig.region,
    clientId: env.SP_API_LWA_CLIENT_ID,
    clientSecret: env.SP_API_LWA_CLIENT_SECRET,
    refreshToken: regionConfig.refreshToken,
  });

  const pg = await getPgClient();
  try {
    const { rows: connRows } = await pg.query<{ connection_id: string }>(
      `INSERT INTO meta.connection (source, label, region, marketplace_ids, status)
       VALUES ('amazon_sp_api', $1, $2, $3, 'active')
       ON CONFLICT (source, label) DO UPDATE
         SET region = EXCLUDED.region, marketplace_ids = EXCLUDED.marketplace_ids,
             last_health_check_at = NOW(), last_health_check_ok = TRUE,
             updated_at = NOW()
       RETURNING connection_id`,
      [`amazon-${regionConfig.region}`, regionConfig.region, regionConfig.marketplaceIds],
    );
    const connectionId = connRows[0]!.connection_id;

    const { rows: runRows } = await pg.query<{ sync_run_id: string }>(
      `INSERT INTO meta.sync_run (connection_id, source, object, mode, window_start, window_end)
       VALUES ($1, 'amazon_sp_api', 'settlement_report', 'backfill', $2, NOW())
       RETURNING sync_run_id`,
      [connectionId, effectiveSince.toISOString()],
    );
    const syncRunId = runRows[0]!.sync_run_id;

    const startedAt = Date.now();
    try {
      const result = await ingestSettlementsWindow({
        spClient,
        pg,
        connectionId,
        syncRunId,
        marketplaceIds,
        createdSince: effectiveSince,
      });

      await pg.query(
        `UPDATE meta.sync_run
           SET finished_at = NOW(), status = 'success',
               rows_fetched = $2, rows_upserted = $3
         WHERE sync_run_id = $1`,
        [syncRunId, result.reportsDiscovered, result.settlementsUpserted + result.linesUpserted],
      );

      const durationMin = ((Date.now() - startedAt) / 60_000).toFixed(1);
      console.log('');
      console.log(
        `Done in ${durationMin} min. ${result.reportsDiscovered} report(s) discovered, ` +
        `${result.reportsSkippedAlreadyIngested} already ingested, ` +
        `${result.reportsParsed} parsed. ${result.settlementsUpserted} settlements / ` +
        `${result.linesUpserted} lines upserted.`,
      );
      if (result.perReport.length > 0) {
        console.log('');
        console.log('Per-report breakdown:');
        for (const r of result.perReport) {
          const dep = r.depositDate?.slice(0, 10) ?? '?';
          const amt = r.totalAmount !== null
            ? `${r.totalAmount.toFixed(2)} ${r.currencyCode ?? ''}`
            : '?';
          console.log(
            `  ${(r.marketplaceId ?? '?').padEnd(15)} ${dep.padEnd(12)} ${amt.padStart(14)}  ${String(r.lines).padStart(6)} lines  (${r.reportId})`,
          );
        }
      }
    } catch (err) {
      await pg.query(
        `UPDATE meta.sync_run
           SET finished_at = NOW(), status = 'failed', error_message = $2
         WHERE sync_run_id = $1`,
        [syncRunId, err instanceof Error ? err.message : String(err)],
      );
      throw err;
    }
  } finally {
    try { await pg.end(); } catch { /* */ }
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
