-- ============================================================================
-- 0018_po_restock_engine.sql
-- Schema hooks for the restock engine (the generate-pos CLI) — the
-- catalogue-wide auto-PO generator that drafts reorder POs for team review.
--
-- Why: the engine writes draft POs into brain.purchase_orders, and must be able
-- to (a) recognise its own prior un-promoted drafts so it can replace them on a
-- re-run, and (b) record a PO line whose physical destination is not yet
-- decided — the operator allocates destinations when they review the draft.
--
-- Three CHECK constraints gain one value each. No data changes; existing rows
-- stay valid. Views over these tables are unaffected (a CHECK is not a view
-- dependency).
--
--   purchase_orders.source_system        + 'restock_engine'
--   purchase_order_lines.destination     + 'unallocated'
--   purchase_order_lines.serves_region   + 'unallocated'
-- ============================================================================

BEGIN;

-- ----------------------------------------------------------------------------
-- 1. brain.purchase_orders.source_system — the engine's drafts must be
--    distinguishable from operator-CSV / Xero / manual POs. The engine keys its
--    idempotent delete-and-replace on source_system = 'restock_engine'.
-- ----------------------------------------------------------------------------
ALTER TABLE brain.purchase_orders DROP CONSTRAINT purchase_orders_source_system_check;
ALTER TABLE brain.purchase_orders ADD CONSTRAINT purchase_orders_source_system_check
    CHECK (source_system IN ('operator_csv', 'xero', 'manual', 'restock_engine'));

COMMENT ON COLUMN brain.purchase_orders.source_system IS
'operator_csv (the import-purchase-orders CLI) | xero (future pull) | manual (direct SQL edit) | restock_engine (a draft PO generated by the generate-pos CLI, pending team review).';

-- ----------------------------------------------------------------------------
-- 2. brain.purchase_order_lines.destination — 'unallocated' is the honest
--    "physical destination not yet decided" state. The engine writes it rather
--    than overloading 'rw_held' (a real RW-held location). The operator sets a
--    real destination when promoting the draft.
-- ----------------------------------------------------------------------------
ALTER TABLE brain.purchase_order_lines DROP CONSTRAINT po_lines_destination_check;
ALTER TABLE brain.purchase_order_lines ADD CONSTRAINT po_lines_destination_check
    CHECK (destination IN (
        'fba_direct', 'uk_3pl_lemonpath', 'usa_awd', 'rw_held', 'unallocated'));

COMMENT ON COLUMN brain.purchase_order_lines.destination IS
'Where this slice of stock physically lands first: fba_direct | uk_3pl_lemonpath | usa_awd | rw_held | unallocated. ''unallocated'' is a draft engine line whose destination the operator has not yet assigned — never a placed PO.';

-- ----------------------------------------------------------------------------
-- 3. brain.purchase_order_lines.serves_region — 'unallocated' likewise, so a
--    draft engine line is not mislabelled 'global'. Draft POs are excluded from
--    brain.po_committed_inventory and /restock-memo's serves_region filter, so
--    an 'unallocated' line never leaks into restock math; the operator sets the
--    real region when promoting.
-- ----------------------------------------------------------------------------
ALTER TABLE brain.purchase_order_lines DROP CONSTRAINT po_lines_serves_region_check;
ALTER TABLE brain.purchase_order_lines ADD CONSTRAINT po_lines_serves_region_check
    CHECK (serves_region IN ('uk_eu', 'na', 'global', 'unallocated'));

COMMENT ON COLUMN brain.purchase_order_lines.serves_region IS
'Which demand region this slice can fulfil: uk_eu | na | global | unallocated. What /restock-memo and brain.po_committed_inventory group on. ''unallocated'' is a draft engine line pending operator review — it carries no region claim and must be resolved before the PO is promoted out of draft.';

-- ----------------------------------------------------------------------------
-- Record this migration
-- ----------------------------------------------------------------------------
INSERT INTO meta.migration_history (filename) VALUES ('0018_po_restock_engine.sql')
ON CONFLICT (filename) DO NOTHING;

COMMIT;
